class AdverticementErrors:
    ID_MSG = "Invalid ID format"
    PUBLISHER_ID_MSG = "Invalid publisher ID format"
    TIME_PERIOD_MSG = "Invalid time period format"
    IS_ACTIVE_MSG = "Invalid is active format"
    COORDINATES_MSG = "Invalid coordinates format"
    ADD_ID_MSG = "Invalid add ID format"
    FILTER_ID_MSG = "Invalid filter ID format"
    FILTER_CATEGORY_ID_MSG = "Invalid filter category ID format"
    VALUE_MSG = "Invalid value format"
    IMAGE_URL_MSG = "Invalid image URL format"
    THUMBNAIL_PHOTO_MSG = "Invalid thumbnail photo format"
    PACKAGE_ID_MSG = "Invalid package ID format"
    DESCRIPTION_MSG = "Invalid description format"
    NUMBER_OF_ADD_MSG = "Invalid number of add format"
    NUM_DAYS_MSG = "Invalid num days format"
    PRICE_MSG = "Invalid price format"
    NAME_MSG = "Invalid name format"
    SYS_USER_ID_MSG = "Invalid sys user ID format"
    
    IMAGE_URL_MSG = "Invalid image URL format"
    TRANSEC_REF_ID_MSG = "Invalid transaction reference ID format"
    STATE_ID_MSG = "Invalid state ID format"
    STATE_MSG = "Invalid state format"
    TRANSACTION_TYPE_MSG = "Invalid transaction type format"
    
    ID_MSG = "Invalid ID format"
    TRANSEC_REF_ID_MSG = "Invalid transaction reference ID format"
    STATE_ID_MSG = "Invalid state ID format"
    STATE_MSG = "Invalid state format"
    TRANSACTION_TYPE_MSG = "Invalid transaction type format"
    DATE_MSG = "Invalid date format"
