class LandingErrors:
    ID_MSG = "Invalid ID format"
    NAME_MSG = "Invalid name format"
    LEVEL_MSG = "Invalid level format"
    CODE_MSG = "Invalid code format"
    PARENT_MSG = "Invalid parent format"
    PARENT_TYPE_MSG = "Invalid parent type format"
    DESCRIPTION_MSG = "Description must be a string"
    REF_ID_MSG = "RefID must be a string"
    TYPE_MSG = "Type must be a string"
    IS_ACTIVE_MSG = "IsActive must be a boolean"
    SQL_STATEMENT_MSG = "SQLStatement must be a string"
    CATEGORY_MSG = "Invalid category format"
    KEY_MSG = "Invalid category format"